### ISSUE TITLE
Compiler warning and misleading for readers

### ISSUE THREAD

**Issue by HenKun** [rikace/fConcBook#11]
https://github.com/rikace/fConcBook/blob/d7477b7ecca31e85f01cf789dccfb05c2495c6e3/Chapter.08/Asynchronous.cs/AsyncOperations.cs#L60

The `async` keyword will result in a compiler warning: "This async method lacks await operators" and this is completely true. The `async` keyword is completely useless here and may confuse readers that are not that familiar with `async await`. It should be removed.

`process` is called synchronously.

**Possibility 1, `process` is a `void` method:**

`Task.Run` returns a `Task` that is finished, when `process` has finished. (Regardless of whether the `async` keyword is used)

**Possibility 2, `process` is an `async void` method (which should strictly be avoided!)**

`Task.Run` returns a `Task` that is set to finished as soon as `process` returns execution to the thread pool thread that was calling `process`, hence, the `Task` returned by `Task.Run` is finished _before_ `process` is finished, which is most probable an unexpected behavior and a bug. `Task.Run` is not able to `await` the passed `process` `Action`. (Again: Regardless of whether the `async` keyword is used)

**Notes to `Task.Run`**

In comparison to `TaskFactory.StartNew`, `Task.Run` was designed to be able to handle `Func<Task>` and `Func<Task<TResult>>` parameters. But that is of no use if an `async void` method is passed to the `Action` overload.

So to put it in a nutshell, the `async` keyword results in no error, it results in a warning. But it's useless in this case and might confuse a reader through pretending there is something called asynchronously. Additionally it might build an unrequired state machine. (But I don't actually know if the compiler omits the state machine if no await is found in the method)

As a side note (which might not be important in this educational case) `Task.Run` should not be used within `async` methods, see https://blog.stephencleary.com/2013/11/taskrun-etiquette-examples-dont-use.html

PS: Besides that I really like the deep dive into the topic in this book!

**Comment by rikace** [comment]
good point, this is a good catch.

I would not use the `Task.Run` in this case, most likely the `process` function is an I/O operation, so I would consider to fix the signature to `Func<byte[], Task> process`, then remove `the Task.Run` and run it as `await process ...`.

I ll take a look at the code and fix it soon

**Comment by HenKun** [comment]
Sounds good. I don't have the book at hand, but I now see that the entire method is `async void`, which should be `async Task` (Unless the book explains something around `async void` with this method).

While assuming process is an I/O operation is OK and to use `Func<byte[], Task> process` would be the way to go, it was not that wrong to assume process is CPU bound. For educational purposes I also think it is OK to use Task.Run in the implementation, but then without the `async` keyword and maybe with a comment like "Through `Task.Run(() => proccess(buffer));` the CPU-bound work `process` is run synchronously on a thread pool thread."

**Comment by rikace** [comment]
This issue has been fixed
