### ISSUE TITLE
cannot run it on ubuntu or Mac

### ISSUE THREAD

**Issue by chakpongchung** [rikace/fConcBook#14]
What is the suggested way to run it without changing any of your code/folder structure?

**Comment by rikace** [comment]
Hi @chakpongchung 
Good timing, I am currently converting the solution to run on Dot NET Core 3.0, which will make the code cross platform.
I have converted almost all chapters. I think that I ll be done in 10-12 days.

if you think is a good idea, I can create a branch with the first 12 chapters converted.

**Comment by chakpongchung** [comment]
I think this is certainly a wonder idea! @rikace (In fact, I am mostly interested in Chapter13.12 and 13.3 )  If the issue for converting Chapter 13 is about the Rx package, I am good with that since I dont need that. I am exploring the concurrency and language construct from F# built-in only.

Meanwhile, I am trying to use windows with visual studio 2019 to  to run your code. After importing it, I see this error in Chapter 1:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\T440\Source\Repos\fConcBook\Common\Utilities\bin\Debug\Utilities.dll' could not be found	QuickSort.cs	C:\Users\T440\Source\Repos\fConcBook\Chapter.01\QuickSort.cs\CSC	1	Active

```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'PerfVis' does not exist in the current context	QuickSort.cs	C:\Users\T440\Source\Repos\fConcBook\Chapter.01\QuickSort.cs\Program.cs	41	Active

```

**Comment by rikace** [comment]
@chakpongchung I am almost done with the conversion.
I ll push the new branch in the next days and I ll notify you.

**Comment by chakpongchung** [comment]
@rikace I see you published the .net core branch!

Would you like to add the instruction to run it? say, on ubuntu or mac

**Comment by rikace** [comment]
@chakpongchung the projects run as any .NET Core project.
Depending on the IDE (Rider, Visual Studio, VS Code, Visual Studio for MAC) or command line (simply execute `dotnet run` in the terminal on the root of the project you need to run).

Does it help?
I tested the projects on Windows and Mac. I am assuming it works on Linux too.

**Comment by chakpongchung** [comment]
```
cpchung:fConcBook$ uname -a
Linux master-node 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
```
cpchung:fConcBook$ dotnet run --project Chapter.13/GraphTasks.FSharp
MSBUILD : error MSB1009: Project file does not exist.
Switch: Chapter.13/GraphTasks.FSharp

The build failed. Fix the build errors and run again.
```

**Comment by rikace** [comment]
This error is correct, since `Chapter.13/GraphTasks.FSharp` is not a file but a directory. To run the project you have to pass the project file.
For example, using the terminal and from the `Chapter.13`, you  should run this command

`dotnet run --project GraphTasks/GraphTasks.FSharp/GraphTasks.FSharp.fsproj`

<img width="574" alt="image" src="https://user-images.githubusercontent.com/183730/74606752-feea9f80-50a0-11ea-9f23-d8bc9b754b5a.png">

**Comment by chakpongchung** [comment]
running the build.sh is having problem. Here is my environment info:

cpchung:fConcBook$ dotnet --list-sdks
3.0.102 [/usr/share/dotnet/sdk]
3.1.101 [/usr/share/dotnet/sdk]

**Comment by rikace** [comment]
did you install `packet` as local (or global) dotnet tool ?

**Comment by chakpongchung** [comment]
I installed nuget. Problem is still the same.

**Comment by rikace** [comment]
Paket is different than nuget.  
In the README file I explain the instructions how to install and use paket to install the dependencies.
Here the reference as in the README file

```
The solution uses Paket as dependency manager for .NET projects. It is recommended to install the Paket tool dotnet tool install --global Paket to restore the packages. After have installed Paket tool, open a terminal and then execute at the root of the solution this command: paket restore . You are now able to build the solution. For more information about look this link Paket .
```

After have installed `paket`, you can run the `build.sh`

**Comment by chakpongchung** [comment]
There are still some errors left but it is pretty much working:

/home/cpchung/.nuget/packages/microsoft.net.compilers.toolset/3.4.0/tasks/netcoreapp2.1/Microsoft.CSharp.Core.targets(59,5): error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly /home/cpchung/.nuget/packages/microsoft.net.compilers.toolset/3.4.0/build/../tasks/netcoreapp2.1/Microsoft.Build.Tasks.CodeAnalysis.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/home/cpchung/code/fsharp/fConcBook/Chapter.02/FunctionalTechniques.CSharp/FunctionalTechniques.CSharp.csproj]
    13 Warning(s)
    8 Error(s)

Thanks!

**Comment by rikace** [comment]
This kind of error is because some weird conflict.
I  see that it tries to load from `/tasks/netcoreapp2.1`  which should  not since this is a solution that runs on DotNet  3.1

try a full clean up and delete all the `Obj` subfolders
