### ISSUE TITLE
Issues running and importing the code in visual studio 2019 on Windows 10

### ISSUE THREAD

**Issue by chakpongchung** [rikace/fConcBook#15]
I am trying to use windows with visual studio 2019 to  to run your code. After importing it, I see this error in Chapter 1:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\T440\Source\Repos\fConcBook\Common\Utilities\bin\Debug\Utilities.dll' could not be found	QuickSort.cs	C:\Users\T440\Source\Repos\fConcBook\Chapter.01\QuickSort.cs\CSC	1	Active

```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'PerfVis' does not exist in the current context	QuickSort.cs	C:\Users\T440\Source\Repos\fConcBook\Chapter.01\QuickSort.cs\Program.cs	41	Active

```

**Comment by rikace** [comment]
the `CSC` issue is due C# Compiler.
I clone a new copy from the repo but I am not able to replicate the error.
Can you provide some details about your environment? 
For example, what version of Visual Studio 2019 are you using ?

Can you compile the project `Common\Utilities` independently and provide the output please
Can you run Visual Studio as administrator, compile the solution and provide the output please

**Comment by chakpongchung** [comment]
I am not sure whether I understand what you mean by compiling `Common\Utilities` independently.

I tried to `rebuild` the `Utillities`, no error, but have warning :

![image](https://user-images.githubusercontent.com/8110904/72670731-18032080-3a0f-11ea-9fe7-ddb3d27b26e1.png)

Then try to `Start` Program.cs in `QuickSort`, seeing this:

![image](https://user-images.githubusercontent.com/8110904/72670750-51d42700-3a0f-11ea-9dc2-ffb992692198.png)


I am using  Visual Studi0 2019 16.4.2 on windows 10, with latest repo on master branch

**Comment by rikace** [comment]
@chakpongchung I am not able to replicate the issue. 
I have compiled the solution in a new Windows 10 Virtual Machine using VS 2019 with latest update.
However, I find a possible issue in the `Functional.fs` project that could be reason of your compile error.
Can you try the compile the branch `update_async_ce`
https://github.com/rikace/fConcBook/tree/update_async_ce

if you still have the same issue, can you please copy & paste here the `output` from the Output window

**Comment by chakpongchung** [comment]
@rikace Added you in linkedin and see whether we can resolve it there. Switching to the other branch doesnt help. Attached is the screenshot. Maybe it is my way of running it or importing it in VS is the problem?

**Comment by rikace** [comment]
Thank I ll ping on LinkedIn,

What's the output in the `Output` windows?   the Tab beside the `Error List`

**Comment by chakpongchung** [comment]
```
1>------ Build started: Project: Functional.cs, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3274: The primary reference "C:\Users\T440\Source\Repos\fConcBook\Common\Utilities\bin\Debug\Utilities.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".
1>  Functional.cs -> C:\Users\T440\Source\Repos\fConcBook\Common\Functional.cs\bin\Debug\Functional.dll
2>------ Build started: Project: FunctionalDataStructures.cs, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3274: The primary reference "C:\Users\T440\Source\Repos\fConcBook\Common\Utilities\bin\Debug\Utilities.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3243: No way to resolve conflict between "System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.
2>  Consider app.config remapping of assembly "System.Collections.Immutable, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.2.1.0" [C:\Users\T440\Source\Repos\fConcBook\packages\System.Collections.Immutable.1.3.1\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll] to Version "1.2.3.0" [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\System.Collections.Immutable.dll] to solve conflict and get rid of warning.
2>C:\Users\T440\Source\Repos\fConcBook\Common\Functional.cs\Concurrency\Atom.cs(37,44,37,51): warning CS0436: The type 'Atom<T>' in 'C:\Users\T440\Source\Repos\fConcBook\Chapter.03\FunctionalDataStructures.cs\..\..\Common\Functional.cs\Concurrency\Atom.cs' conflicts with the imported type 'Atom<T>' in 'Functional, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\T440\Source\Repos\fConcBook\Chapter.03\FunctionalDataStructures.cs\..\..\Common\Functional.cs\Concurrency\Atom.cs'.
2>C:\Users\T440\Source\Repos\fConcBook\Chapter.03\FunctionalDataStructures.cs\Program.cs(46,24,46,37): error CS0433: The type 'ImmutableList' exists in both 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2>C:\Users\T440\Source\Repos\fConcBook\Chapter.03\FunctionalDataStructures.cs\Program.cs(51,27,51,40): error CS0433: The type 'ImmutableList' exists in both 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2>C:\Users\T440\Source\Repos\fConcBook\Chapter.03\FunctionalDataStructures.cs\Program.cs(64,13,64,17): error CS0103: The name 'Demo' does not exist in the current context
2>C:\Users\T440\Source\Repos\fConcBook\Chapter.03\FunctionalDataStructures.cs\Program.cs(74,13,74,17): error CS0103: The name 'Demo' does not exist in the current context
========== Build: 1 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

Basically, the problem I found is that the whole project is targeting at different framework in different files.

I installed the corresponding versions, keeping multiple of them installed in my windows machine, still not working as shown above.

Unfortunately, this plugin cannot be installed for this reason:

![image](https://user-images.githubusercontent.com/8110904/72957138-7c581400-3d70-11ea-969c-cfa636d7de28.png)

**Comment by rikace** [comment]
The CI pipeline picks what framework the project targets.
I would recommend to have all the projects targeting the same framework. 
From your last error message, seems that the system is picking 4.6.1

Today I tried to move all the projects to target 4.8 and I was able to build without any problem. I believe there is something faulting in the .NET Sdk installled.
Can you verify run "Miscrosoft Visual Studio Installer" and check/install the frameworks 

<img width="805" alt="image" src="https://user-images.githubusercontent.com/183730/73035866-ae708100-3e17-11ea-8424-ff088236b947.png">

**Comment by chakpongchung** [comment]
I see, you are using studio 2017, I am using 2019. Thats why that plugin can be installed in your machine.
