### ISSUE TITLE
2.18 WebCrawlerMemoized

### ISSUE THREAD

**Issue by tim-huang61** [rikace/fConcBook#19]
Hi, I tried WebCrawlerMemoized, it seems not to work, this example runs WebCrawlerMemoized but it still runs WebCrawler if the cache has the key. I think the cause, maybe WebCrawler got data by yield return, but WebCrawlerMemoized got value by return.

**Comment by rikace** [comment]
Hi @tim-huang61 
Thank you for the feedback.

I have tried to run the example 2.18 that uses the WebCrawlerMemoized. 
I have updated the code `memoize` to provide some logs.

      ```
  // Listing 2.12 A simple example that clarifies how memoization works
        public static Func<T, R> Memoize<T, R>(Func<T, R> func) where T : IComparable //#A
        {
            Dictionary<T, R> cache = new Dictionary<T, R>();    //#B
            return arg =>                                       //#C
            {
                if (cache.ContainsKey(arg))
                {
                    Console.WriteLine($"Calling item cached {arg} - Time {DateTime.Now}");
                    return cache[arg];
                }

                Console.WriteLine($"Calling item no cached {arg} - Time {DateTime.Now}");
                return (cache[arg] = func(arg));                //#F
            };
        }
```

The output seems that the code works as expected 


<img width="553" alt="image" src="https://user-images.githubusercontent.com/183730/110221301-85834200-7e99-11eb-8408-ca9bde4f6108.png">


do you have an example that I can use to replicate your issue?

**Comment by tim-huang61** [comment]
Hi @rikace, thank your answer.
I have updated `GetWebContent` to print logs.
```
private static string GetWebContent(string url)
 {
            using (var wc = new WebClient())
            {
                Console.WriteLine($"Get Web Content {url} - Time {DateTime.Now}");
                return wc.DownloadString(new Uri(url));
            }
}
```
the output  
![image](https://user-images.githubusercontent.com/3638404/110444574-2a02bf80-80f8-11eb-9e48-d9c66af0342d.png)

**Comment by rikace** [comment]
Hi @tim-huang61 
I missed this answer.

The example is targeting the `WebCrawler` function. Indeed, since the function returns a lazy collection (IEnumerable), the `WebContent` is going to be re-process every time.

the alternative approach could be update the `WebCrawler` function as 

```
        public static List<string> WebCrawler(string url) //#A
        {
            IEnumerable<string> WebCrawler(string url)
            {
                string content = GetWebContent(url);
                if (content != null)
                    yield return content;

                foreach (string item in AnalyzeHtmlContent(content))
                    yield return GetWebContent(item);
            }

            return WebCrawler(url).ToList();
        }
```

**Comment by rikace** [comment]
if you want, you can create a PR or I can do it

**Comment by tim-huang61** [comment]
Hi @rikace, thanks for your answer.
I have sent a PR to u. 👍🏻
