### ISSUE TITLE
Safari Books Online

### ISSUE THREAD

**Issue by hickford** [rikace/fConcBook#5]
Hi. Will the book [Concurrency in .NET](https://www.manning.com/books/concurrency-in-dot-net) be available on Safari Books Online? https://www.safaribooksonline.com/library/publisher/manning-publications/

**Comment by rikace** [comment]
Yes it will be, I think by the end of July 

Regards,
Riccardo Terrell  

Cell Phone: 304 579 5728
Twitter: @trikace
GitHub: https://github.com/rikace
Blog: http://www.rickyterrell.com
Linkedin: http://linkedin.com/in/riterrell/

Microsoft Most Valuable Professional  <https://mvp.microsoft.com/en-us/PublicProfile/5002015?fullName=Riccardo%20Terrell>

 <https://mvp.microsoft.com/en-us/PublicProfile/5002015?fullName=Riccardo%20Terrell>





 <https://mvp.microsoft.com/en-us/PublicProfile/5002015?fullName=Riccardo%20Terrell>Book:  <https://mvp.microsoft.com/en-us/PublicProfile/5002015?fullName=Riccardo%20Terrell>Functional Concurrency in .NET <https://www.manning.com/books/functional-concurrency-in-dotnet>

**Comment by hickford** [comment]
Brilliant, I look forward to reading it

**Comment by hickford** [comment]
Please let me know when it's up

**Comment by hickford** [comment]
Any news? 

Emailed support@safaribooksonline.com

**Comment by hickford** [comment]
Wahey! https://learning.oreilly.com/library/view/concurrency-in-net/9781617292996/
