### ISSUE TITLE
Chapter 1 - CPU has nearly reached the speed of light

### ISSUE THREAD

**Issue by Miggleness** [rikace/fConcBook#6]
Just a minor typo correction in the book.  Apologize if this isn't the avenue for this stuff.  Really enjoying the book.

_The speed of light is about 3e8 meters per second, which means that data can be propagated around 0.30 cm (about a foot)_

I believe that should be 30 cm.

**Comment by rikace** [comment]
That's correct. I mentioned the correction on the book forum.
The publisher will fix the errata.

I am glad you are enjoying the book, thank you for the feedback
