### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by Miggleness** [rikace/fConcBook#7]
Hi again.  I see in your readme that you're adding support for .NET core. Let me now if I can send PRs.  I'm running on a Mac so I'm updating C# samples to .NET core and use BenchmarkDotNet for perf measurement.

**Comment by rikace** [comment]
That would be great, please open a PR.
I am working on the UI implementation, instead of using WPF for example I am aiming to use a local web-server and web-sockets for bidirectional communication. 
Thank you

**Comment by rikace** [comment]
create new branch here 
https://github.com/rikace/fConcBook/tree/dotnet_core
